### ISSUE TITLE
Sent speed auto-scaling not working

### ISSUE THREAD

**Issue by LHuisingh** [nayuki/NetPerSec#1]
When I opened NetPerSec today the Sent window was showing an average of 190Kbit/s in the text box.  However, the vertical scaling had a midpoint of 17.180 Gbit/s and a maximum of 34.360 Gbit/s.  See attached screenshot.  

![image](https://user-images.githubusercontent.com/31296055/51152933-f3d09a80-1822-11e9-9244-d7cc82212225.png)

The system tray icon did show what appears to be an accurate autoscaling preview.  See attached.
![image](https://user-images.githubusercontent.com/31296055/51152970-1f538500-1823-11e9-9fde-4729872d3fa4.png)

**Comment by nayuki** [comment]
Hi, thank you for taking the time to describe the problem. I should note that most bugs are from the original author of NetPerSec nearly two decades ago, and I fixed some but not all of them.

As I don't have a Windows C++ development environment set up anymore, nor the time to maintain this project, I'm afraid I can't do anything for you right now.
