### ISSUE TITLE
Settings are not saved across program restarts.

### ISSUE THREAD

**Issue by Maelstorm1973** [nayuki/NetPerSec#2]
When running as an ordinary user (non-admin), settings are not saved.  When the program is closed and then opened again, it reverts to defaults.

**Comment by nayuki** [comment]
I think I know what you mean. Did you put your netpersec.exe in Program Files which is a protected folder, or in some random user-accessible folder? I'm sorry, I don't know Windows APIs and semantics well enough to troubleshoot this situation effectively.
